version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: hr_postgres
    environment:
      POSTGRES_DB: ytech_hr
      POSTGRES_USER: hr_app_user
      POSTGRES_PASSWORD: LocalPostgres12345!
    ports:
      - "5432:5432"

  web:
    build: .
    container_name: hr_app
    command: >
      sh -c "
      python backend/manage.py migrate &&
      python backend/manage.py seed_demo &&
      python backend/manage.py runserver 0.0.0.0:8000
      "
    ports:
      - "8000:8000"
    depends_on:
      - postgres
