version: '3.8'

services:

  postgres:
    image: postgres:15
    container_name: hr_postgres
    restart: always

    environment:
      POSTGRES_DB: ytech_hr
      POSTGRES_USER: hr_app_user
      POSTGRES_PASSWORD: LocalPostgres12345!

    ports:
      - "5432:5432"

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U hr_app_user -d ytech_hr"]
      interval: 5s
      timeout: 5s
      retries: 10

    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    container_name: hr_app
    restart: always

    environment:
      DATABASE_URL: postgres://hr_app_user:LocalPostgres12345!@postgres:5432/ytech_hr
      DJANGO_DEBUG: "1"
      DJANGO_ALLOWED_HOSTS: "localhost,127.0.0.1,0.0.0.0,192.168.142.142"

    ports:
      - "8000:8000"

    depends_on:
      postgres:
        condition: service_healthy

    command: >
      sh -c "
      echo 'Waiting for database...' &&
      sleep 5 &&
      python backend/manage.py migrate &&
      python backend/manage.py collectstatic --noinput || true &&
      python backend/manage.py runserver 0.0.0.0:8000
      "

volumes:
  postgres_data:
